name: test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch, tag or commit'     
        required: true
        default: 'master'
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: download artifacts
    runs-on: ubuntu-latest
    steps:
      -
        name: Log inputs
        run: echo "Hello ${{ github.event.inputs.branch }}!"
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          repo: arturcic/libgit2sharp.nativebinaries
          branch: ${{ github.event.inputs.branch }}
          name: NuGet package
          
