name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      RID: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            name: win-x86
            param: -x86
          - os: windows-2019
            name: win-x64
            param: -x64
          - os: windows-2019
            name: win-arm64
            param: -arm64
          - os: ubuntu-20.04
            name: linux-x64
          - os: ubuntu-20.04
            name: linux-musl-x64
          - os: ubuntu-20.04
            name: linux-arm64
          - os: ubuntu-20.04
            name: linux-musl-arm
          - os: ubuntu-20.04
            name: linux-musl-arm64
          - os: ubuntu-20.04
            name: linux-arm
          - os: macos-10.15
            name: osx-x64
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Build Windows
        if: runner.os == 'Windows'
        run: cd native; ./build.libgit2.ps1 ${{ matrix.param }}
      - name: Build macOS        
        if: runner.os == 'macOS'
        run: cd native; ./build.libgit2.sh
      - name: Setup QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
        if: matrix.name == 'linux-musl-arm' || matrix.name == 'linux-musl-arm64'
      - name: Build Linux
        if: runner.os == 'Linux'
        run: cd native; ./dockerbuild.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{ matrix.name }}
          path: native/nuget.package/runtimes/${{ matrix.name }}
