name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: gittools/build-images:ubuntu.20.04-sdk-6.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: check code
        run: dotnet run --project ./libgit2sharp/LibGit2Sharp.LoadTest/LibGit2Sharp.LoadTest.csproj
